import { globalIgnores } from 'eslint/config'
import js from '@eslint/js'
import { defineConfigWithVueTs, vueTsConfigs } from '@vue/eslint-config-typescript'
import pluginVue from 'eslint-plugin-vue'
import pluginVitest from '@vitest/eslint-plugin'

/**
 * Correctness, not formatting.
 *
 * `vue/flat/essential` rather than `flat/recommended`: the recommended set adds
 * ~260 warnings to the existing `src/`, and every one of them is about where a
 * bracket goes. Auto-fixing them would rewrite most of the templates in a single
 * commit and make `git blame` useless for no defensive gain. What this config is
 * for is the class of problem `vue-tsc` compiles without complaint — an import
 * nothing reads, a `v-for` with no `:key`, a mutated prop.
 *
 * Prettier is likewise absent, unlike backend/eslint.config.mjs, for the same
 * reason. If the frontend ever adopts it, that should be its own commit.
 */
export default defineConfigWithVueTs(
  globalIgnores(['dist/**', 'dev-dist/**', 'coverage/**', '.lighthouseci/**']),

  {
    name: 'app/files-to-lint',
    files: ['**/*.{ts,mts,tsx,vue}'],
  },

  // Same base as backend/eslint.config.mjs. It is also what makes the
  // `require-yield` disable in ask.spec.ts mean something — that generator
  // throws instead of yielding, on purpose.
  js.configs.recommended,
  pluginVue.configs['flat/essential'],
  vueTsConfigs.recommended,

  {
    name: 'app/rules',
    rules: {
      // The reason for adding a linter at all: an import or a local that nothing
      // reads is dead weight the type-checker happily compiles. `_`-prefixed
      // names stay allowed so a deliberately-ignored callback argument does not
      // have to be worked around.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          ignoreRestSiblings: true,
        },
      ],

      // Not in the recommended set. The terminal command registry is a lot of
      // hand-written string handling, and `==` there is a bug rather than a
      // style opinion. `null` stays exempt so `x == null` keeps working as the
      // idiomatic null-or-undefined check.
      eqeqeq: ['error', 'always', { null: 'ignore' }],
    },
  },

  {
    // Vendored shadcn-vue primitives. They are regenerated by the CLI, so the
    // single-word filenames it produces are not ours to rename.
    name: 'app/ui-primitives',
    files: ['src/components/ui/**'],
    rules: {
      'vue/multi-word-component-names': 'off',
    },
  },

  {
    ...pluginVitest.configs.recommended,
    name: 'app/tests',
    files: ['src/**/__tests__/**/*.{ts,tsx}', 'src/**/*.{test,spec}.{ts,tsx}'],
    rules: {
      ...pluginVitest.configs.recommended.rules,
      // Vitest's `expect(value, message)` second argument is the label printed
      // when an assertion inside a loop fails; the rule defaults to Jest's
      // single-argument signature and flags every one of them.
      'vitest/valid-expect': ['error', { maxArgs: 2 }],
      // Aimed at try/catch assertions that silently never run. The two uses here
      // are data-dependent guards inside a loop, and both are commented as such.
      'vitest/no-conditional-expect': 'off',
    },
  },
)
